# Generated by Django 4.1.3 on 2022-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutProveedor', models.CharField(max_length=10)),
                ('dvProveedor', models.CharField(max_length=1)),
                ('nombreProveedor', models.CharField(max_length=50)),
                ('fonoProveedor', models.CharField(max_length=20)),
                ('correoProveedor', models.EmailField(max_length=50)),
                ('direccionProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.TextField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcionProducto', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proveedor')),
            ],
        ),
    ]
